// Converts the Postgres JSON exports in ../_migration/data into a D1 seed file.
//
// Conversions applied:
//   boolean        -> 1 / 0
//   integer[]      -> JSON array stored as TEXT
//   text[]         -> JSON array stored as TEXT
//   uuid           -> TEXT (already a string in the export)
//   timestamps     -> left byte-for-byte as Postgres emitted them, so the app
//                     keeps parsing exactly the strings PostgREST used to return
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const DATA = join(here, '..', '..', '_migration', 'data')
const OUT = join(here, '..', 'migrations', '0002_seed.sql')

const read = (name) => {
  const raw = readFileSync(join(DATA, `${name}.jsonl`), 'utf8')
  return raw
    .split('\n')
    .filter((line) => line.trim() !== '')
    .map((line, i) => {
      try {
        return JSON.parse(line)
      } catch (err) {
        throw new Error(`${name}.jsonl line ${i + 1}: ${err.message}`)
      }
    })
}

const lit = (v) => {
  if (v === null || v === undefined) return 'NULL'
  if (typeof v === 'boolean') return v ? '1' : '0'
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL'
  if (Array.isArray(v) || typeof v === 'object') return lit(JSON.stringify(v))
  return `'${String(v).replace(/'/g, "''")}'`
}

const chunks = []
const emit = (s) => chunks.push(s)

/** Emit batched multi-row INSERTs for one table. */
function insertAll(table, cols, rows, { batch = 40 } = {}) {
  if (!rows.length) {
    emit(`-- ${table}: no rows`)
    return 0
  }
  for (let i = 0; i < rows.length; i += batch) {
    const slice = rows.slice(i, i + batch)
    const values = slice
      .map((r) => `  (${cols.map((c) => lit(r[c])).join(', ')})`)
      .join(',\n')
    emit(
      `INSERT INTO ${table} (${cols.join(', ')}) VALUES\n${values};`,
    )
  }
  return rows.length
}

const counts = {}

emit('-- ABPM Trainer System — data migrated from self-hosted Supabase Postgres.')
emit('-- Generated by scripts/build-seed.mjs — do not edit by hand.')
emit('')
emit('PRAGMA defer_foreign_keys = TRUE;')
emit('')

// --- users (from auth.users) ------------------------------------------------
const authUsers = read('auth_users')
emit('-- users (was auth.users; bcrypt hashes carried over verbatim)')
counts.users = insertAll(
  'users',
  ['id', 'email', 'password_hash', 'email_confirmed_at', 'created_at', 'updated_at', 'last_sign_in_at', 'raw_user_meta_data'],
  authUsers.map((u) => ({
    id: u.id,
    email: u.email,
    password_hash: u.encrypted_password,
    email_confirmed_at: u.email_confirmed_at,
    created_at: u.created_at,
    updated_at: u.updated_at,
    last_sign_in_at: u.last_sign_in_at,
    raw_user_meta_data: JSON.stringify(u.raw_user_meta_data ?? {}),
  })),
)
emit('')

// --- RBAC -------------------------------------------------------------------
const roles = read('roles')
emit('-- roles')
counts.roles = insertAll('roles', ['id', 'name', 'description', 'level', 'created_at', 'updated_at'], roles)
emit('')

const permissions = read('permissions')
emit('-- permissions')
counts.permissions = insertAll('permissions', ['id', 'name', 'resource', 'action', 'description', 'created_at'], permissions)
emit('')

const rolePermissions = read('role_permissions')
emit('-- role_permissions')
counts.role_permissions = insertAll('role_permissions', ['id', 'role_id', 'permission_id', 'created_at'], rolePermissions)
emit('')

// --- reference --------------------------------------------------------------
const regions = read('regions')
emit('-- regions')
counts.regions = insertAll('regions', ['id', 'name', 'code', 'training_centers', 'active_trainers'], regions)
emit('')

// --- trainers ---------------------------------------------------------------
const userIds = new Set(authUsers.map((u) => u.id))
const roleIds = new Set(roles.map((r) => r.id))
const trainers = read('trainers')
let orphanUser = 0
let orphanRole = 0
for (const t of trainers) {
  if (t.user_id && !userIds.has(t.user_id)) { t.user_id = null; orphanUser++ }
  if (t.role_id && !roleIds.has(t.role_id)) { t.role_id = null; orphanRole++ }
}
emit('-- trainers')
counts.trainers = insertAll(
  'trainers',
  ['id', 'name', 'rank', 'status', 'specialization', 'created_at', 'role_id', 'is_active', 'last_login', 'user_id', 'region', 'updated_at', 'department'],
  trainers,
)
emit('')

// --- domain -----------------------------------------------------------------
const events = read('events')
emit('-- events')
counts.events = insertAll('events', ['id', 'name', 'category', 'start_date', 'end_date', 'description', 'color', 'created_at'], events)
emit('')

const trainerIds = new Set(trainers.map((t) => t.id))
const schedules = read('schedules')
let orphanSchedule = 0
for (const s of schedules) {
  if (s.trainer_id !== null && !trainerIds.has(s.trainer_id)) { s.trainer_id = null; orphanSchedule++ }
  s.availability = JSON.stringify(s.availability ?? [])
}
emit('-- schedules (availability text[] -> JSON array)')
counts.schedules = insertAll('schedules', ['id', 'trainer_id', 'date', 'availability', 'status', 'notes', 'created_at', 'updated_at'], schedules, { batch: 60 })
emit('')

const pt = read('physical_training')
for (const r of pt) r.participants = JSON.stringify(r.participants ?? [])
emit('-- physical_training (participants integer[] -> JSON array)')
counts.physical_training = insertAll('physical_training', ['id', 'date', 'training_type', 'in_charge', 'participants', 'time_slot', 'created_at'], pt)
emit('')

const ra = read('religious_activities')
for (const r of ra) r.participants = JSON.stringify(r.participants ?? [])
emit('-- religious_activities (participants integer[] -> JSON array)')
counts.religious_activities = insertAll('religious_activities', ['id', 'date', 'activity', 'in_charge', 'participants', 'created_at'], ra)
emit('')

const dorm = read('dormitory_assignments')
let orphanDorm = 0
for (const d of dorm) {
  if (d.trainer_id !== null && !trainerIds.has(d.trainer_id)) { d.trainer_id = null; orphanDorm++ }
}
emit('-- dormitory_assignments')
counts.dormitory_assignments = insertAll('dormitory_assignments', ['id', 'room_id', 'trainer_id', 'check_in', 'check_out', 'status', 'created_at'], dorm)
emit('')

const ts = read('training_sessions')
emit('-- training_sessions')
counts.training_sessions = insertAll('training_sessions', ['id', 'date', 'type', 'trainer_id', 'status', 'time_slot', 'created_at'], ts)
emit('')

// Keep AUTOINCREMENT sequences ahead of the migrated ids.
emit('-- realign AUTOINCREMENT counters with the migrated max(id)')
for (const t of ['regions', 'trainers', 'events', 'schedules', 'physical_training', 'religious_activities', 'dormitory_assignments', 'training_sessions']) {
  emit(`INSERT INTO sqlite_sequence (name, seq) SELECT '${t}', COALESCE((SELECT MAX(id) FROM ${t}), 0)\n  WHERE NOT EXISTS (SELECT 1 FROM sqlite_sequence WHERE name = '${t}');`)
  emit(`UPDATE sqlite_sequence SET seq = COALESCE((SELECT MAX(id) FROM ${t}), 0) WHERE name = '${t}';`)
}

writeFileSync(OUT, chunks.join('\n') + '\n')

console.log('wrote', OUT)
console.table(counts)
console.log('total rows:', Object.values(counts).reduce((a, b) => a + b, 0))
if (orphanUser || orphanRole || orphanSchedule || orphanDorm) {
  console.log('nulled dangling FKs ->', { 'trainers.user_id': orphanUser, 'trainers.role_id': orphanRole, 'schedules.trainer_id': orphanSchedule, 'dormitory_assignments.trainer_id': orphanDorm })
}
